server {
    server_name testing.bot-atelier.ru;

    client_max_body_size 20M;

    location = /index.html {
        root /opt/testing-bots/frontend/dist;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires -1;
    }

    location /assets/ {
        root /opt/testing-bots/frontend/dist;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        root /opt/testing-bots/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    location ^~ /api/internal/ {
        deny all;
        return 403;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location /uploads/ {
        alias /opt/testing-bots/backend/src/uploads/;
        expires 30d;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/testing.bot-atelier.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/testing.bot-atelier.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = testing.bot-atelier.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name testing.bot-atelier.ru;
    return 404; # managed by Certbot


}
